### ISSUE TITLE
Translate Q code to Spanish language

### ISSUE THREAD

**Issue by domnantas** [domnantas/ARManual#42]
# The problem
The [Q Code page](https://armanual.org/q-code/) should be translated to Spanish language

# Requirements
- [ ] Copy `ARManual/q-code/README.md` to `ARManual/es/q-code/README.md`
- [ ] Translate the table headings
- [ ] Translate table content
- [ ] Change the link from `/q-code/` to `/es/q-code` [here](https://github.com/LRMD/ARManual/blob/6fcdfeaa3251b4cf8854adb725e2daa8f1b8bab1/ARManual/.vuepress/config.ts#L176)

**Comment by jimmyunnamed** [comment]
I would like to work on this. Working on the PR now.

**Comment by taicoding** [comment]
Hi there, 
I'm a native spanish speaker and I would like to work on this issue. 
Please assign it to me.

**Comment by domnantas** [comment]
@taicoding sure!

**Comment by domnantas** [comment]
Your change is live! https://armanual.org/es/q-code/

**Comment by taicoding** [comment]
Awesome! 
It was a pleasure to collaborate
